name: newdestinations
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  timezone: ^0.9.3
  http: ^0.13.6
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  dio: ^5.4.3+1
  google_maps_flutter: ^2.0.10
  google_maps_webservice: ^0.0.15
  location: ^6.0.2
  google_place: ^0.4.3
  url_launcher: ^6.3.0
  provider: ^6.1.2
  equatable: ^2.0.0
  flutter_bloc: ^8.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data/
    - assets/data/newAdventures.json
    - assets/data/freeEvents.json
    - assets/data/lowBudgetAirlines.json
    - assets/data/countryTabs.json
    - assets/data/emergencyNumbers.json
    - assets/data/citiesNearby.json
