name: newdestinations
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  timezone: ^0.9.3
  http: ^0.13.6
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/newAdventures.json
    - assets/data/freeEvents.json
    - assets/data/lowBudgetAirlines.json
    - assets/data/countryTabs.json
